server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userKeyResolver}"

                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth

            - id: task-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/tasks/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userKeyResolver}"

                - name: CircuitBreaker
                  args:
                    name: taskServiceCB
                    fallbackUri: forward:/fallback/task

            - id: analytics-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/analytics/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userKeyResolver}"

                - name: CircuitBreaker
                  args:
                    name: analyticsServiceCB
                    fallbackUri: forward:/fallback/analytics

            - id: notification-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userKeyResolver}"

                - name: CircuitBreaker
                  args:
                    name: notificationServiceCB
                    fallbackUri: forward:/fallback/notification

  data:
    redis:
      host: localhost
      port: 6379

resilience4j:
  circuitbreaker:
    instances:

      authServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      taskServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      analyticsServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      notificationServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

jwt:
  secret:

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: unrestricted